"""Adiciona abrangencia e unidades a terceirizados

Revision ID: 01f80cfb9012
Revises: 5294e772d5ef
Create Date: 2025-12-18 09:49:22.738578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f80cfb9012'
down_revision = '5294e772d5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terceirizados_unidades',
    sa.Column('terceirizado_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['terceirizado_id'], ['terceirizados.id'], name=op.f('fk_terceirizados_unidades_terceirizado_id_terceirizados')),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], name=op.f('fk_terceirizados_unidades_unidade_id_unidades')),
    sa.PrimaryKeyConstraint('terceirizado_id', 'unidade_id', name=op.f('pk_terceirizados_unidades'))
    )
    with op.batch_alter_table('terceirizados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('abrangencia_global', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_terceirizados_unidade_id_unidades'), type_='foreignkey')
        batch_op.drop_column('unidade_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terceirizados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_terceirizados_unidade_id_unidades'), 'unidades', ['unidade_id'], ['id'])
        batch_op.drop_column('abrangencia_global')

    op.drop_table('terceirizados_unidades')
    # ### end Alembic commands ###
