"""Add health status to ConfiguracaoWhatsApp

Revision ID: 1414d4af1853
Revises: 4ac78186cf98
Create Date: 2025-12-31 04:02:51.220991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1414d4af1853'
down_revision = '4ac78186cf98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_configuracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_saude', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ultima_verificacao', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_configuracao', schema=None) as batch_op:
        batch_op.drop_column('ultima_verificacao')
        batch_op.drop_column('status_saude')

    # ### end Alembic commands ###
