"""add_ordens_compra_lista_table

Revision ID: 2369b605a525
Revises: add_resposta_nao_cadastrado
Create Date: 2026-03-04 16:04:18.800480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2369b605a525'
down_revision = 'add_resposta_nao_cadastrado'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listas_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('periodicidade_dias', sa.Integer(), nullable=True),
    sa.Column('criador_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['criador_id'], ['usuarios.id'], name=op.f('fk_listas_compra_criador_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listas_compra'))
    )
    op.create_table('lista_compra_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=True),
    sa.Column('descricao_livre', sa.String(length=300), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('categoria_compra', sa.String(length=50), nullable=True),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], name=op.f('fk_lista_compra_itens_estoque_id_estoque')),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_lista_compra_itens_fornecedor_id_fornecedores')),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_compra.id'], name=op.f('fk_lista_compra_itens_lista_id_listas_compra')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lista_compra_itens'))
    )
    op.create_table('ordens_compra_lista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lista_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=True),
    sa.Column('unidade_destino_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lista_id'], ['listas_compra.id'], name=op.f('fk_ordens_compra_lista_lista_id_listas_compra')),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], name=op.f('fk_ordens_compra_lista_solicitante_id_usuarios')),
    sa.ForeignKeyConstraint(['unidade_destino_id'], ['unidades.id'], name=op.f('fk_ordens_compra_lista_unidade_destino_id_unidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ordens_compra_lista'))
    )
    with op.batch_alter_table('comunicacoes_fornecedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_comunicacoes_data'))
        batch_op.drop_index(batch_op.f('idx_comunicacoes_fornecedor_fk'))
        batch_op.drop_index(batch_op.f('idx_comunicacoes_pedido'))

    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_equipamentos_qrcode_externo'), sqlite_where=sa.text('qrcode_externo IS NOT NULL'))
        batch_op.create_unique_constraint(batch_op.f('uq_equipamentos_qrcode_externo'), ['qrcode_externo'])
        batch_op.drop_column('data_aquisicao')
        batch_op.drop_column('descricao')
        batch_op.drop_column('codigo')
        batch_op.drop_column('custo_aquisicao')
        batch_op.drop_column('status')

    with op.batch_alter_table('historico_notificacoes', schema=None) as batch_op:
        batch_op.alter_column('mimetype',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('url_midia_local',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_megaapi_id'))

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.drop_column('custo_momento')

    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.drop_column('avaliacao')
        batch_op.drop_column('data_inicio')
        batch_op.drop_column('tempo_execucao_minutos')
        batch_op.drop_column('data_prevista')

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ordem_lista_id', sa.Integer(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_token_aprovacao'))
        batch_op.create_unique_constraint(batch_op.f('uq_pedidos_compra_token_aprovacao'), ['token_aprovacao'])
        batch_op.create_foreign_key(batch_op.f('fk_pedidos_compra_ordem_lista_id_ordens_compra_lista'), 'ordens_compra_lista', ['ordem_lista_id'], ['id'])
        batch_op.drop_column('numero_pedido')
        batch_op.drop_column('valor_total')

    with op.batch_alter_table('whatsapp_regras_automacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notificar_usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('para_desconhecidos', sa.Boolean(), nullable=True))
        batch_op.alter_column('palavra_chave',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_regras_automacao', schema=None) as batch_op:
        batch_op.alter_column('palavra_chave',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('para_desconhecidos')
        batch_op.drop_column('notificar_usuario_id')

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('numero_pedido', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_pedidos_compra_ordem_lista_id_ordens_compra_lista'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_pedidos_compra_token_aprovacao'), type_='unique')
        batch_op.create_index(batch_op.f('idx_token_aprovacao'), ['token_aprovacao'], unique=1)
        batch_op.drop_column('ordem_lista_id')

    with op.batch_alter_table('ordens_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_prevista', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('tempo_execucao_minutos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('data_inicio', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('avaliacao', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_momento', sa.NUMERIC(precision=10, scale=2), nullable=True))

    with op.batch_alter_table('historico_notificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_megaapi_id'), ['megaapi_id'], unique=False)
        batch_op.alter_column('url_midia_local',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('mimetype',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('equipamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'operacional'"), nullable=True))
        batch_op.add_column(sa.Column('custo_aquisicao', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('codigo', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('data_aquisicao', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_equipamentos_qrcode_externo'), type_='unique')
        batch_op.create_index(batch_op.f('ix_equipamentos_qrcode_externo'), ['qrcode_externo'], unique=1, sqlite_where=sa.text('qrcode_externo IS NOT NULL'))

    with op.batch_alter_table('comunicacoes_fornecedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_comunicacoes_pedido'), ['pedido_compra_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comunicacoes_fornecedor_fk'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_comunicacoes_data'), ['data_envio'], unique=False)

    op.drop_table('ordens_compra_lista')
    op.drop_table('lista_compra_itens')
    op.drop_table('listas_compra')
    # ### end Alembic commands ###
