"""Add criado_em to HistoricoNotificacao

Revision ID: 3a53dda54dd3
Revises: 1414d4af1853
Create Date: 2025-12-31 04:05:54.533780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a53dda54dd3'
down_revision = '1414d4af1853'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_notificacoes', schema=None) as batch_op:
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
