"""add_target_audience_to_regras

Revision ID: 3ec26333d72d
Revises: 2369b605a525
Create Date: 2026-03-04 16:28:49.586821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec26333d72d'
down_revision = '2369b605a525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_regras_automacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('para_terceirizados', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('para_usuarios', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_whatsapp_regras_automacao_notificar_usuario_id_usuarios'), 'usuarios', ['notificar_usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_regras_automacao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_whatsapp_regras_automacao_notificar_usuario_id_usuarios'), type_='foreignkey')
        batch_op.drop_column('para_usuarios')
        batch_op.drop_column('para_terceirizados')

    # ### end Alembic commands ###
