"""Add routing fields to RegrasAutomacao

Revision ID: 415b1ea5b49d
Revises: c54b967eeaeb
Create Date: 2025-12-31 03:51:49.255565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415b1ea5b49d'
down_revision = 'c54b967eeaeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_regras_automacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encaminhar_para_perfil', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('funcao_sistema', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_regras_automacao', schema=None) as batch_op:
        batch_op.drop_column('funcao_sistema')
        batch_op.drop_column('encaminhar_para_perfil')

    # ### end Alembic commands ###
