"""Allow nullable chamado_id in HistoricoNotificacao

Revision ID: 4ac78186cf98
Revises: 415b1ea5b49d
Create Date: 2025-12-31 03:54:00.906317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac78186cf98'
down_revision = '415b1ea5b49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remetente', sa.String(length=20), nullable=True))
        batch_op.alter_column('chamado_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('destinatario',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_notificacoes', schema=None) as batch_op:
        batch_op.alter_column('destinatario',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('chamado_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('remetente')

    # ### end Alembic commands ###
