"""make_estoque_id_nullable

Revision ID: 510095ed5e12
Revises: add_whatsapp_respostas
Create Date: 2026-03-03 09:43:27.011447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510095ed5e12'
down_revision = 'add_whatsapp_respostas'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.alter_column('estoque_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.alter_column('estoque_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
