"""Add ssid_wifi to unidades table

Revision ID: 5294e772d5ef
Revises: afacfdb19cc8
Create Date: 2025-12-16 21:30:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5294e772d5ef'
down_revision = 'afacfdb19cc8'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add ssid_wifi to unidades
    # Verifica se a coluna já existe antes de adicionar (opcional, mas seguro)
    # op.add_column('unidades', sa.Column('ssid_wifi', sa.String(length=50), nullable=True))
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssid_wifi', sa.String(length=50), nullable=True))

    # 2. Check and add foto_perfil to usuarios if not exists
    # Como não podemos verificar facilmente se existe via código simples aqui sem reflection,
    # assumimos que se o usuário pediu, não existe no BD, ou usamos ignore_exisiting
    # Mas o comando seguro é apenas tentar adicionar. Se já existe, vai falhar a migration, 
    # então o ideal seria usar inspetor, mas migrations devem ser determinísticas.
    # O usuário pediu para VERIFICAR. Se o model tem, o alembic gera o add.
    
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_column('ssid_wifi')
    # ### end Alembic commands ###
