"""Add unidade_id to Terceirizado

Revision ID: afacfdb19cc8
Revises: f9d8c9ff71cf
Create Date: 2025-12-15 19:23:02.632700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afacfdb19cc8'
down_revision = 'f9d8c9ff71cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terceirizados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_terceirizados_unidade_id_unidades'), 'unidades', ['unidade_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('terceirizados', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_terceirizados_unidade_id_unidades'), type_='foreignkey')
        batch_op.drop_column('unidade_id')

    # ### end Alembic commands ###
