"""Add WhatsApp module models

Revision ID: c54b967eeaeb
Revises: 01f80cfb9012
Create Date: 2025-12-31 03:32:46.929382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c54b967eeaeb'
down_revision = '01f80cfb9012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_encrypted', sa.LargeBinary(length=200), nullable=True),
    sa.Column('circuit_breaker_threshold', sa.Integer(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_configuracao'))
    )
    op.create_table('whatsapp_metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=True),
    sa.Column('total_enviadas', sa.Integer(), nullable=True),
    sa.Column('taxa_entrega', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tempo_medio_resposta', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_metricas'))
    )
    with op.batch_alter_table('whatsapp_metricas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_metricas_data_hora'), ['data_hora'], unique=False)

    op.create_table('whatsapp_regras_automacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palavra_chave', sa.String(length=50), nullable=False),
    sa.Column('tipo_correspondencia', sa.String(length=20), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('resposta_texto', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_regras_automacao'))
    )
    with op.batch_alter_table('whatsapp_regras_automacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_regras_automacao_palavra_chave'), ['palavra_chave'], unique=False)

    op.create_table('whatsapp_tokens_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.Column('entidade_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_tokens_acesso'))
    )
    with op.batch_alter_table('whatsapp_tokens_acesso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_tokens_acesso_expira_em'), ['expira_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_whatsapp_tokens_acesso_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_whatsapp_tokens_acesso_usado'), ['usado'], unique=False)

    op.create_table('whatsapp_estados_conversa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=True),
    sa.Column('estado_atual', sa.String(length=50), nullable=True),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados_externos.id'], name=op.f('fk_whatsapp_estados_conversa_chamado_id_chamados_externos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_estados_conversa'))
    )
    with op.batch_alter_table('whatsapp_estados_conversa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whatsapp_estados_conversa_telefone'), ['telefone'], unique=False)

    with op.batch_alter_table('historico_notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direcao', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('mensagem_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('prioridade', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_historico_notificacoes_mensagem_hash'), ['mensagem_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_notificacoes_prioridade'), ['prioridade'], unique=False)

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.alter_column('fornecedor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.alter_column('fornecedor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('historico_notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_notificacoes_prioridade'))
        batch_op.drop_index(batch_op.f('ix_historico_notificacoes_mensagem_hash'))
        batch_op.drop_column('prioridade')
        batch_op.drop_column('mensagem_hash')
        batch_op.drop_column('direcao')

    with op.batch_alter_table('whatsapp_estados_conversa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_estados_conversa_telefone'))

    op.drop_table('whatsapp_estados_conversa')
    with op.batch_alter_table('whatsapp_tokens_acesso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_tokens_acesso_usado'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_tokens_acesso_token'))
        batch_op.drop_index(batch_op.f('ix_whatsapp_tokens_acesso_expira_em'))

    op.drop_table('whatsapp_tokens_acesso')
    with op.batch_alter_table('whatsapp_regras_automacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_regras_automacao_palavra_chave'))

    op.drop_table('whatsapp_regras_automacao')
    with op.batch_alter_table('whatsapp_metricas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whatsapp_metricas_data_hora'))

    op.drop_table('whatsapp_metricas')
    op.drop_table('whatsapp_configuracao')
    # ### end Alembic commands ###
