"""Modulo 3 Terceirizados

Revision ID: f9d8c9ff71cf
Revises: 
Create Date: 2025-12-15 11:18:56.544911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d8c9ff71cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias_estoque')),
    sa.UniqueConstraint('nome', name=op.f('uq_categorias_estoque_nome'))
    )
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('prazo_medio_entrega_dias', sa.Float(), nullable=True),
    sa.Column('total_pedidos_entregues', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fornecedores'))
    )
    op.create_table('terceirizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_empresa', sa.String(length=150), nullable=True),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('especialidades', sa.Text(), nullable=True),
    sa.Column('avaliacao_media', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_servicos', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terceirizados'))
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('faixa_ip_permitida', sa.String(length=255), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unidades')),
    sa.UniqueConstraint('nome', name=op.f('uq_unidades_nome'))
    )
    op.create_table('equipamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], name=op.f('fk_equipamentos_unidade_id_unidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_equipamentos'))
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('unidade_medida', sa.String(length=5), nullable=False),
    sa.Column('quantidade_atual', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('quantidade_minima', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('unidade_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_estoque.id'], name=op.f('fk_estoque_categoria_id_categorias_estoque')),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], name=op.f('fk_estoque_unidade_id_unidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estoque')),
    sa.UniqueConstraint('codigo', name=op.f('uq_estoque_codigo'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade_padrao_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_padrao_id'], ['unidades.id'], name=op.f('fk_usuarios_unidade_padrao_id_unidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email')),
    sa.UniqueConstraint('username', name=op.f('uq_usuarios_username'))
    )
    op.create_table('catalogo_fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('preco_atual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('prazo_estimado_dias', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], name=op.f('fk_catalogo_fornecedores_estoque_id_estoque')),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_catalogo_fornecedores_fornecedor_id_fornecedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalogo_fornecedores'))
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_os', sa.String(length=20), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('equipamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo_manutencao', sa.String(length=20), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('descricao_problema', sa.Text(), nullable=False),
    sa.Column('descricao_solucao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('prazo_conclusao', sa.DateTime(), nullable=False),
    sa.Column('fotos_antes', sa.JSON(), nullable=True),
    sa.Column('fotos_depois', sa.JSON(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipamento_id'], ['equipamentos.id'], name=op.f('fk_ordens_servico_equipamento_id_equipamentos')),
    sa.ForeignKeyConstraint(['tecnico_id'], ['usuarios.id'], name=op.f('fk_ordens_servico_tecnico_id_usuarios')),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], name=op.f('fk_ordens_servico_unidade_id_unidades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ordens_servico')),
    sa.UniqueConstraint('numero_os', name=op.f('uq_ordens_servico_numero_os'))
    )
    op.create_table('pedidos_compra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_chegada', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], name=op.f('fk_pedidos_compra_estoque_id_estoque')),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_pedidos_compra_fornecedor_id_fornecedores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pedidos_compra'))
    )
    op.create_table('registros_ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_entrada', sa.DateTime(), nullable=False),
    sa.Column('data_hora_saida', sa.DateTime(), nullable=True),
    sa.Column('ip_origem_entrada', sa.String(length=45), nullable=False),
    sa.Column('ip_origem_saida', sa.String(length=45), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], name=op.f('fk_registros_ponto_unidade_id_unidades')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_registros_ponto_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registros_ponto'))
    )
    with op.batch_alter_table('registros_ponto', schema=None) as batch_op:
        batch_op.create_index('idx_unidade_data', ['unidade_id', 'data_hora_entrada'], unique=False)
        batch_op.create_index('idx_usuario_data', ['usuario_id', 'data_hora_entrada'], unique=False)

    op.create_table('anexos_os',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=255), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('tamanho_kb', sa.Integer(), nullable=True),
    sa.Column('upload_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], name=op.f('fk_anexos_os_os_id_ordens_servico')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anexos_os'))
    )
    op.create_table('chamados_externos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_chamado', sa.String(length=20), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('terceirizado_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('prioridade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('prazo_combinado', sa.DateTime(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('valor_orcado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avaliacao', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], name=op.f('fk_chamados_externos_criado_por_usuarios')),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], name=op.f('fk_chamados_externos_os_id_ordens_servico')),
    sa.ForeignKeyConstraint(['terceirizado_id'], ['terceirizados.id'], name=op.f('fk_chamados_externos_terceirizado_id_terceirizados')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chamados_externos')),
    sa.UniqueConstraint('numero_chamado', name=op.f('uq_chamados_externos_numero_chamado'))
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('estoque_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo_movimentacao', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('observacao', sa.String(length=255), nullable=True),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estoque_id'], ['estoque.id'], name=op.f('fk_movimentacoes_estoque_estoque_id_estoque')),
    sa.ForeignKeyConstraint(['os_id'], ['ordens_servico.id'], name=op.f('fk_movimentacoes_estoque_os_id_ordens_servico')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_movimentacoes_estoque_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacoes_estoque'))
    )
    op.create_table('historico_notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chamado_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('destinatario', sa.String(length=20), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('status_envio', sa.String(length=20), nullable=True),
    sa.Column('resposta_api', sa.Text(), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chamado_id'], ['chamados_externos.id'], name=op.f('fk_historico_notificacoes_chamado_id_chamados_externos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historico_notificacoes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_notificacoes')
    op.drop_table('movimentacoes_estoque')
    op.drop_table('chamados_externos')
    op.drop_table('anexos_os')
    with op.batch_alter_table('registros_ponto', schema=None) as batch_op:
        batch_op.drop_index('idx_usuario_data')
        batch_op.drop_index('idx_unidade_data')

    op.drop_table('registros_ponto')
    op.drop_table('pedidos_compra')
    op.drop_table('ordens_servico')
    op.drop_table('catalogo_fornecedores')
    op.drop_table('usuarios')
    op.drop_table('estoque')
    op.drop_table('equipamentos')
    op.drop_table('unidades')
    op.drop_table('terceirizados')
    op.drop_table('fornecedores')
    op.drop_table('categorias_estoque')
    # ### end Alembic commands ###
